# Generated by Django 5.1.4 on 2024-12-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCreamShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shop', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('popolarity', models.IntegerField(blank=True, null=True)),
                ('opening_hours', models.CharField(max_length=20)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Киоск с мороженым',
                'verbose_name_plural': 'Киоски с мороженым',
            },
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ShopId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppModels.icecreamshop')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженые',
            },
        ),
    ]
