# Generated by Django 5.1.3 on 2024-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='about_customers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
