# Generated by Django 5.1.3 on 2025-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('DR', 'Драма'), ('CO', 'Комедия'), ('TH', 'Триллер'), ('HO', 'Ужасы'), ('AC', 'Боевик'), ('FN', 'Фэнтези'), ('SF', 'Научная фантастика')], max_length=2)),
                ('year', models.IntegerField()),
                ('counry', models.CharField(max_length=255)),
                ('view', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
