# Generated by Django 5.1.3 on 2025-02-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='counry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='zhanr',
        ),
    ]
