# Generated by Django 5.1.3 on 2025-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_counry_film_country_rename_genre_film_zhanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
